import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
import {AppService} from "../app-service";

/*
 Generated class for the SkuDetailsServiceProvider provider.

 See https://angular.io/docs/ts/latest/guide/dependency-injection.html
 for more info on providers and Angular DI.
 */
@Injectable()
export class SkuDetailsServiceProvider {

  private data = {
    "status": "success",
    "message": "Sku details successfully fetched",
    "data": {
      "data": [{
        "id": 3398375,
        "sku_code": "H150_Brown",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Women's Brown Handbag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h150_brown_1.jpg",
        "in_stock": 86,
        "seller_in_stock": 76,
        "marketplace_in_stock": 10,
        "to_ship": 14,
        "product_family": "Hand Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FBGFUR0039", "default"],
          ["FRJDHDBG00000135", "default"],
          ["H150SB_Brown", "default"],
          ["H150SH_Brown", "default"],
          ["H150TB_Brown", "default"],
          ["H150_Brown", "default"]
        ],
        "channels": [{
          "id": 492764254,
          "status_on_channel": 0,
          "price_on_channel": 3000,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Brown Handbag",
          "item_ref": "0928QA5TUQY",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351254,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 76,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Brown Handbag",
          "item_ref": "H150_Brown",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 501320452,
          "status_on_channel": 1,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 2,
          "quantity_on_channel": 50,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Hand-held Bag",
          "item_ref": "LSTHMBEH2TFGCBQJ8GFMVPPM3",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 500902019,
          "status_on_channel": 1,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Brown Faux Leather Sling Bag",
          "item_ref": "SDL822537571",
          "is_fba": 0,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747318,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 76,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H150_Brown",
          "item_ref": "11541281",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489389367,
          "status_on_channel": 0,
          "price_on_channel": 1632.6,
          "sku_code_on_channel": "FRJDHDBG00000135",
          "sla_on_channel": 0,
          "quantity_on_channel": 71,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Brown_Onesize_H150_Brown_FRJDHDBG00000135",
          "item_ref": "FRJDHDBG00000135",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 485575444,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 76,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Brown Handbag",
          "item_ref": "61326114",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 492764254,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01JGLA6DE",
            "price_on_channel": 3000,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 0,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Women's Brown Handbag",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509351254,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 76,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Women's Brown Handbag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11557": {
            "id": 501320452,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEH2TFGCBQJ8GF",
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 50,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Hand-held Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "11795": {
            "id": 500902019,
            "status_on_channel": 1,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 0,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Brown Faux Leather Sling Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "12641": {
            "id": 489747318,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 76,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H150_Brown",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "13056": {
            "id": 489389367,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1632.6,
            "sku_code_on_channel": "FRJDHDBG00000135",
            "quantity_on_channel": 71,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Brown_Onesize_H150_Brown_FRJDHDBG00000135",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12212": {
            "id": 485575444,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-women-s-brown-handbag-BAGFUR-JADEN-WOFUR-134141BC12F6B5",
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Brown",
            "quantity_on_channel": 76,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Women's Brown Handbag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }, {
        "id": 3249284,
        "sku_code": "H150_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Tan Handbag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h150_tan_1.jpg",
        "in_stock": 84,
        "seller_in_stock": 70,
        "marketplace_in_stock": 14,
        "to_ship": 42,
        "product_family": "Hand Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FBGFUR0001", "default"],
          ["FRJDHDBG00000148", "default"],
          ["H150SB_Tan", "default"],
          ["H150SH_Tan", "default"],
          ["H150TB_Tan", "default"],
          ["H150_Tan", "default"]
        ],
        "channels": [{
          "id": 497657852,
          "status_on_channel": 0,
          "price_on_channel": 3000,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 14,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Handbag",
          "item_ref": "0928QA5XU2Y",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509350886,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 71,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Handbag",
          "item_ref": "H150_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 493206594,
          "status_on_channel": 1,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 2,
          "quantity_on_channel": 50,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Hand-held Bag",
          "item_ref": "LSTHMBEJYZ5RC7VT7RUZAAMHJ",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492681277,
          "status_on_channel": 1,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
          "item_ref": "SDL234766173",
          "is_fba": 0,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 491820376,
          "status_on_channel": 0,
          "price_on_channel": 1632.6,
          "sku_code_on_channel": "FRJDHDBG00000148",
          "sla_on_channel": 0,
          "quantity_on_channel": 89,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H150_Tan_FRJDHDBG00000148",
          "item_ref": "FRJDHDBG00000148",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747320,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 70,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H150_Tan",
          "item_ref": "11169778",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 486954042,
          "status_on_channel": 0,
          "price_on_channel": 1999,
          "sku_code_on_channel": "H150_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 71,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Handbag",
          "item_ref": "66173472",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 497657852,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01HGS6AY8",
            "price_on_channel": 3000,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 14,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Tan Handbag",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509350886,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 71,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Tan Handbag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11557": {
            "id": 493206594,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEJYZ5RC7VT7RU",
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 50,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Hand-held Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "11795": {
            "id": 492681277,
            "status_on_channel": 1,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 0,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "13056": {
            "id": 491820376,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1632.6,
            "sku_code_on_channel": "FRJDHDBG00000148",
            "quantity_on_channel": 89,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H150_Tan_FRJDHDBG00000148",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12641": {
            "id": 489747320,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 70,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H150_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 486954042,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-tan-handbag-BAGFUR-JADEN-TAFUR-134141C4C63EA0",
            "price_on_channel": 1999,
            "sku_code_on_channel": "H150_Tan",
            "quantity_on_channel": 71,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Tan Handbag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }, {
        "id": 3249310,
        "sku_code": "H182_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Tan Tote Bag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h182_tan_1.jpg",
        "in_stock": 60,
        "seller_in_stock": 34,
        "marketplace_in_stock": 26,
        "to_ship": 40,
        "product_family": "Tote Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FRJDHDBG00000190", "default"],
          ["FTTFUR0024", "default"],
          ["H182SH_Tan", "default"],
          ["H182TB_Tan", "default"],
          ["H182_Tan", "default"],
          ["H182_TanA", "default"]
        ],
        "channels": [{
          "id": 496704538,
          "status_on_channel": 0,
          "price_on_channel": 2600,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 26,
          "mrp_on_channel": 2600,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Handbag(Brown,H182_Tan)",
          "item_ref": "0928QA6369A",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509194270,
          "status_on_channel": 0,
          "price_on_channel": 1649,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 1649,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Faux Leather Tote Bag",
          "item_ref": null,
          "is_fba": 1,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351151,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 34,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Tote Bag",
          "item_ref": "H182_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 501320657,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 2,
          "quantity_on_channel": 34,
          "mrp_on_channel": 2600,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Hand-held Bag",
          "item_ref": "LSTHMBEJYZ4QRJG8NBVQFNSC5",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492285419,
          "status_on_channel": 0,
          "price_on_channel": 1414.92,
          "sku_code_on_channel": "FRJDHDBG00000190",
          "sla_on_channel": 0,
          "quantity_on_channel": 29,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H182_Tan_FRJDHDBG00000190",
          "item_ref": "FRJDHDBG00000190",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747428,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 34,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H182_Tan",
          "item_ref": "11169804",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 486954005,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H182_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 34,
          "mrp_on_channel": 2600,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Handbag",
          "item_ref": "66173435",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 496704538,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01HGS6I0E",
            "price_on_channel": 2600,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 26,
            "mrp_on_channel": 2600,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Women's Handbag(Brown,H182_Tan)",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "11795": {
            "id": 509194270,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1649,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 0,
            "mrp_on_channel": 1649,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Tan Faux Leather Tote Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "18236": {
            "id": 509351151,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 34,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Tan Tote Bag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11557": {
            "id": 501320657,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEJYZ4QRJG8NBV",
            "price_on_channel": 1599,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 34,
            "mrp_on_channel": 2600,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Hand-held Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "13056": {
            "id": 492285419,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1414.92,
            "sku_code_on_channel": "FRJDHDBG00000190",
            "quantity_on_channel": 29,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H182_Tan_FRJDHDBG00000190",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12641": {
            "id": 489747428,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 34,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H182_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 486954005,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-tan-handbag-BAGFUR-JADEN-TAFUR-134141BEC3E480",
            "price_on_channel": 1599,
            "sku_code_on_channel": "H182_Tan",
            "quantity_on_channel": 34,
            "mrp_on_channel": 2600,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Tan Handbag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }, {
        "id": 4881347,
        "sku_code": "BM04_Brown",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 0,
        "warehouse_is_low_stock": 0,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Laptop Backpack for Men by Fur Jaden  Brown Colour Fashionable College and Office Backpack made of Water Resistant Artificial Leather",
        "image_path": "https:\/\/skuimages.s3.amazonaws.com\/4881347.jpeg",
        "in_stock": 55,
        "seller_in_stock": 49,
        "marketplace_in_stock": 6,
        "to_ship": 4,
        "product_family": "Men's Backpacks",
        "hsncode": null,
        "sku_aliases": [
          ["BM04_Brown", "default"]
        ],
        "channels": [{
          "id": 501510517,
          "status_on_channel": 0,
          "price_on_channel": 3200,
          "sku_code_on_channel": "BM04_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 6,
          "mrp_on_channel": 3200,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Casual Backpack for Men by Fur Jaden, Brown Colour Fashionable College and Office Backpack made of Water Resistant Artificial Leather",
          "item_ref": "0512SW99GGA",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 510512043,
          "status_on_channel": 1,
          "price_on_channel": 1399,
          "sku_code_on_channel": "BM04_Brown",
          "sla_on_channel": 2,
          "quantity_on_channel": 48,
          "mrp_on_channel": 3200,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden 15 inch Laptop Backpack",
          "item_ref": "LSTLTBETYJ7UDJR7K2EC2O2RN",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 501510517,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B0719DSF37",
            "price_on_channel": 3200,
            "sku_code_on_channel": "BM04_Brown",
            "quantity_on_channel": 6,
            "mrp_on_channel": 3200,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Casual Backpack for Men by Fur Jaden, Brown Colour Fashionable College and Office Backpack made of Water Resistant Artificial Leather",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "11557": {
            "id": 510512043,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/LTBETYJ7UDJR7K2E",
            "price_on_channel": 1399,
            "sku_code_on_channel": "BM04_Brown",
            "quantity_on_channel": 48,
            "mrp_on_channel": 3200,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden 15 inch Laptop Backpack",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          }
        }
      }, {
        "id": 4503810,
        "sku_code": "H221_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Tan Tote Bag for Women",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%2BJaden\/h221_tan_1.jpg",
        "in_stock": 50,
        "seller_in_stock": 42,
        "marketplace_in_stock": 8,
        "to_ship": 3,
        "product_family": "Tote Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FRJDHDBG00000246", "default"],
          ["H221_Tan", "default"]
        ],
        "channels": [{
          "id": 496291064,
          "status_on_channel": 0,
          "price_on_channel": 2500,
          "sku_code_on_channel": "H221_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 6,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Casual Tote Bag cum Shoulder Purse with Tassels",
          "item_ref": null,
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351417,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H221_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 42,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Tote Bag for Women",
          "item_ref": "H221_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 499704461,
          "status_on_channel": 0,
          "price_on_channel": 1360.5,
          "sku_code_on_channel": "FRJDHDBG00000246",
          "sla_on_channel": 0,
          "quantity_on_channel": 42,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H221_Tan_FRJDHDBG00000246",
          "item_ref": "FRJDHDBG00000246",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 496263463,
          "status_on_channel": 1,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H221_Tan",
          "sla_on_channel": 2,
          "quantity_on_channel": 42,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tote",
          "item_ref": "LSTHMBES2UHTPBEKZCQ3X5MUQ",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 495984589,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H221_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 42,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H221_Tan",
          "item_ref": "14869760",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 495833961,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H221_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 42,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Tote Bag For Women",
          "item_ref": "102195422",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 496291064,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 2500,
            "sku_code_on_channel": "H221_Tan",
            "quantity_on_channel": 6,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Casual Tote Bag cum Shoulder Purse with Tassels",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509351417,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H221_Tan",
            "quantity_on_channel": 42,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Tan Tote Bag for Women",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "13056": {
            "id": 499704461,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1360.5,
            "sku_code_on_channel": "FRJDHDBG00000246",
            "quantity_on_channel": 42,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H221_Tan_FRJDHDBG00000246",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "11557": {
            "id": 496263463,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBES2UHTPBEKZCQ",
            "price_on_channel": 1599,
            "sku_code_on_channel": "H221_Tan",
            "quantity_on_channel": 42,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Tote",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "12641": {
            "id": 495984589,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H221_Tan",
            "quantity_on_channel": 42,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H221_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 495833961,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-tan-tote-bag-for-women-BAGFUR-JADEN-TAFUR-1341418FEB3C76",
            "price_on_channel": 1599,
            "sku_code_on_channel": "H221_Tan",
            "quantity_on_channel": 42,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Tan Tote Bag For Women",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }, {
        "id": 3249289,
        "sku_code": "H152_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Tan Croc Handheld Bag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h152_tan_1.jpg",
        "in_stock": 49,
        "seller_in_stock": 39,
        "marketplace_in_stock": 10,
        "to_ship": 15,
        "product_family": "Hand Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FBGFUR0143", "default"],
          ["FRJDHDBG00000085", "default"],
          ["H152SB_Tan", "default"],
          ["H152SH_Tan", "default"],
          ["H152_Tan", "default"]
        ],
        "channels": [{
          "id": 496563540,
          "status_on_channel": 0,
          "price_on_channel": 3000,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 8,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Handbag(Tan,H152_Tan)",
          "item_ref": "0928QA5Z504",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351329,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Croc Handheld Bag",
          "item_ref": "H152_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492681265,
          "status_on_channel": 1,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
          "item_ref": "SDL491602928",
          "is_fba": 0,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747329,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H152_Tan",
          "item_ref": "11169783",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 488555901,
          "status_on_channel": 0,
          "price_on_channel": 1632.6,
          "sku_code_on_channel": "FRJDHDBG00000085",
          "sla_on_channel": 0,
          "quantity_on_channel": 43,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H152_Tan_FRJDHDBG00000085",
          "item_ref": "FRJDHDBG00000085",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 486954008,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Croc Handheld Bag",
          "item_ref": "66173438",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 481693598,
          "status_on_channel": 1,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Tan",
          "sla_on_channel": 2,
          "quantity_on_channel": 39,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Hand-held Bag",
          "item_ref": "LSTHMBEJYZ3DPAPSAWRLNUHTE",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 496563540,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01HGS6TPI",
            "price_on_channel": 3000,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 8,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Women's Handbag(Tan,H152_Tan)",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509351329,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 39,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Tan Croc Handheld Bag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11795": {
            "id": 492681265,
            "status_on_channel": 1,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 0,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "12641": {
            "id": 489747329,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 39,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H152_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "13056": {
            "id": 488555901,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1632.6,
            "sku_code_on_channel": "FRJDHDBG00000085",
            "quantity_on_channel": 43,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H152_Tan_FRJDHDBG00000085",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12212": {
            "id": 486954008,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-tan-croc-handheld-bag-BAGFUR-JADEN-TAFUR-134141F2A645E4",
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 39,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Tan Croc Handheld Bag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          },
          "11557": {
            "id": 481693598,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEJYZ3DPAPSAWR",
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Tan",
            "quantity_on_channel": 39,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Hand-held Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          }
        }
      }, {
        "id": 3249288,
        "sku_code": "H152_Brown",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Brown Croc Handheld Bag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h152_brown_1.jpg",
        "in_stock": 48,
        "seller_in_stock": 38,
        "marketplace_in_stock": 10,
        "to_ship": 12,
        "product_family": "Hand Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FBGFUR0005", "default"],
          ["FRJDHDBG00000185", "default"],
          ["H152SB_Brown", "default"],
          ["H152SH_Brown", "default"],
          ["H152_Brown", "default"]
        ],
        "channels": [{
          "id": 499057864,
          "status_on_channel": 0,
          "price_on_channel": 3000,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 10,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Handbag(Brown,H152_Brown)",
          "item_ref": "0928QA5YWUS",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509350898,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 38,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Brown Croc Handheld Bag",
          "item_ref": "H152_Brown",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492810392,
          "status_on_channel": 1,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Brown Faux Leather Shoulder Bag",
          "item_ref": "SDL895114126",
          "is_fba": 0,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492285411,
          "status_on_channel": 0,
          "price_on_channel": 1632.6,
          "sku_code_on_channel": "FRJDHDBG00000185",
          "sla_on_channel": 0,
          "quantity_on_channel": 40,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Brown_Onesize_H152_Brown_FRJDHDBG00000185",
          "item_ref": "FRJDHDBG00000185",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747327,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 38,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H152_Brown",
          "item_ref": "11169782",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 486954029,
          "status_on_channel": 0,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 0,
          "quantity_on_channel": 38,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Brown Croc Handheld Bag",
          "item_ref": "66173459",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 481693618,
          "status_on_channel": 1,
          "price_on_channel": 1949,
          "sku_code_on_channel": "H152_Brown",
          "sla_on_channel": 2,
          "quantity_on_channel": 38,
          "mrp_on_channel": 3000,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Hand-held Bag",
          "item_ref": "LSTHMBEJYZ3DMYUHTGCIOFRU7",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 499057864,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01HGS6QY2",
            "price_on_channel": 3000,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 10,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Women's Handbag(Brown,H152_Brown)",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509350898,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 38,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Brown Croc Handheld Bag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11795": {
            "id": 492810392,
            "status_on_channel": 1,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 0,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Brown Faux Leather Shoulder Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "13056": {
            "id": 492285411,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1632.6,
            "sku_code_on_channel": "FRJDHDBG00000185",
            "quantity_on_channel": 40,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Brown_Onesize_H152_Brown_FRJDHDBG00000185",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12641": {
            "id": 489747327,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 38,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H152_Brown",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 486954029,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-brown-croc-handheld-bag-BAGFUR-JADEN-BRFUR-134141F6A6A6D2",
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 38,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Brown Croc Handheld Bag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          },
          "11557": {
            "id": 481693618,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEJYZ3DMYUHTGC",
            "price_on_channel": 1949,
            "sku_code_on_channel": "H152_Brown",
            "quantity_on_channel": 38,
            "mrp_on_channel": 3000,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Hand-held Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          }
        }
      }, {
        "id": 4111721,
        "sku_code": "H210_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Women's Tan Shouder HandBag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%2BJaden\/h210_tan_1.jpg",
        "in_stock": 46,
        "seller_in_stock": 31,
        "marketplace_in_stock": 15,
        "to_ship": -3,
        "product_family": "Hand Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FRJDHDBG00000206", "default"],
          ["H210A_Tan", "default"],
          ["H210B_Tan", "default"],
          ["H210C_Tan", "default"],
          ["H210SB_Tan", "default"],
          ["H210TB_Tan", "default"],
          ["H210_Tan", "default"]
        ],
        "channels": [{
          "id": 499668603,
          "status_on_channel": 0,
          "price_on_channel": 2800,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 14,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Shoulder Purse with Sling",
          "item_ref": "1228QSPH7Q4",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351316,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Tan Shouder HandBag",
          "item_ref": "H210_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 501320409,
          "status_on_channel": 1,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 2,
          "quantity_on_channel": 31,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Shoulder Bag",
          "item_ref": "LSTHMBEQ75J7C4SBG7AJCRGGR",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 500901919,
          "status_on_channel": 1,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
          "item_ref": "SDL962969752",
          "is_fba": 0,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 495721724,
          "status_on_channel": 0,
          "price_on_channel": 1523.76,
          "sku_code_on_channel": "FRJDHDBG00000206",
          "sla_on_channel": 0,
          "quantity_on_channel": 37,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H210_Tan_FRJDHDBG00000206",
          "item_ref": "FRJDHDBG00000206",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492575810,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210A_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Shoulder Purse with Sling",
          "item_ref": "0111SBLBUUM",
          "is_fba": 0,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492575815,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210B_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Shoulder Purse with Sling",
          "item_ref": "0111SBLCHUY",
          "is_fba": 0,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492575820,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210C_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Shoulder Purse with Sling",
          "item_ref": "0111SBLD1DG",
          "is_fba": 0,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492346941,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 2800,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Tan Shouder Handbag",
          "item_ref": "88759293",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492285404,
          "status_on_channel": 0,
          "price_on_channel": 1899,
          "sku_code_on_channel": "H210_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 31,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H210_Tan",
          "item_ref": "13906135",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 492575820,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01MY75XXF",
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210C_Tan",
            "quantity_on_channel": 31,
            "mrp_on_channel": 2800,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Handbags for Women by Fur Jaden, Tan Colour Branded Ladies Shoulder Purse with Sling",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509351316,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210_Tan",
            "quantity_on_channel": 31,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Women's Tan Shouder HandBag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11557": {
            "id": 501320409,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/HMBEQ75J7C4SBG7A",
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210_Tan",
            "quantity_on_channel": 31,
            "mrp_on_channel": 2800,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Shoulder Bag",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "11795": {
            "id": 500901919,
            "status_on_channel": 1,
            "url_on_channel": null,
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210_Tan",
            "quantity_on_channel": 0,
            "mrp_on_channel": 2800,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "13056": {
            "id": 495721724,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1523.76,
            "sku_code_on_channel": "FRJDHDBG00000206",
            "quantity_on_channel": 37,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H210_Tan_FRJDHDBG00000206",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12212": {
            "id": 492346941,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-women-s-tan-shouder-handbag-BAGFUR-JADEN-WOFUR-134141DC275C1E",
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210_Tan",
            "quantity_on_channel": 31,
            "mrp_on_channel": 2800,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Women's Tan Shouder Handbag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          },
          "12641": {
            "id": 492285404,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1899,
            "sku_code_on_channel": "H210_Tan",
            "quantity_on_channel": 31,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H210_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          }
        }
      }, {
        "id": 3398447,
        "sku_code": "H183_Tan",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Women's Modern Tan Tote Bag",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%20Jaden\/h183_tan_1.jpg",
        "in_stock": 45,
        "seller_in_stock": 26,
        "marketplace_in_stock": 19,
        "to_ship": 1,
        "product_family": "Tote Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FRJDHDBG00000191", "default"],
          ["FTTFUR0098", "default"],
          ["H183SB_Tan", "default"],
          ["H183SH_Tan", "default"],
          ["H183TB_Tan", "default"],
          ["H183_Tan", "default"]
        ],
        "channels": [{
          "id": 508490746,
          "status_on_channel": 0,
          "price_on_channel": 2200,
          "sku_code_on_channel": "H183_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 18,
          "mrp_on_channel": 2200,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Combo Of Tote And Sling Bag (,H183_Tan)",
          "item_ref": "0928QA63HEY",
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 501208928,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H183_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 1599,
          "favicon_path": "\/img\/icons\/icon_snapdeal.png",
          "channel_title": "Snapdeal.com",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
          "item_ref": null,
          "is_fba": 1,
          "channel_id": 11795,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 14,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351331,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H183_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 26,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Modern Tan Tote Bag",
          "item_ref": "H183_Tan",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 492285420,
          "status_on_channel": 0,
          "price_on_channel": 1414.92,
          "sku_code_on_channel": "FRJDHDBG00000191",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Tan_Onesize_H183_Tan_FRJDHDBG00000191",
          "item_ref": "FRJDHDBG00000191",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 489747431,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H183_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 26,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H183_Tan",
          "item_ref": "11541352",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 485575511,
          "status_on_channel": 0,
          "price_on_channel": 1599,
          "sku_code_on_channel": "H183_Tan",
          "sla_on_channel": 0,
          "quantity_on_channel": 26,
          "mrp_on_channel": 2200,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women's Modern Tan Hand Bag",
          "item_ref": "61326181",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 508490746,
            "status_on_channel": 0,
            "url_on_channel": "http:\/\/www.amazon.in\/dp\/B01JGLCGBE",
            "price_on_channel": 2200,
            "sku_code_on_channel": "H183_Tan",
            "quantity_on_channel": 18,
            "mrp_on_channel": 2200,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Fur Jaden Women's Combo Of Tote And Sling Bag (,H183_Tan)",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "11795": {
            "id": 501208928,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H183_Tan",
            "quantity_on_channel": 0,
            "mrp_on_channel": 1599,
            "favicon_path": "\/img\/icons\/icon_snapdeal.png",
            "channel_title": "Snapdeal.com",
            "title_on_channel": "Fur Jaden Tan Faux Leather Shoulder Bag",
            "channel_id": 11795,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 14
          },
          "18236": {
            "id": 509351331,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H183_Tan",
            "quantity_on_channel": 26,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Women's Modern Tan Tote Bag",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "13056": {
            "id": 492285420,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1414.92,
            "sku_code_on_channel": "FRJDHDBG00000191",
            "quantity_on_channel": 0,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Tan_Onesize_H183_Tan_FRJDHDBG00000191",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12641": {
            "id": 489747431,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1599,
            "sku_code_on_channel": "H183_Tan",
            "quantity_on_channel": 26,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H183_Tan",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 485575511,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-women-s-modern-tan-hand-bag-BAGFUR-JADEN-WOFUR-134141D0FD90D3",
            "price_on_channel": 1599,
            "sku_code_on_channel": "H183_Tan",
            "quantity_on_channel": 26,
            "mrp_on_channel": 2200,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Women's Modern Tan Hand Bag",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }, {
        "id": 4518640,
        "sku_code": "H224_Black",
        "is_low_Stock": 0,
        "low_stock_level": 0,
        "warehouse_stock_out": 1,
        "warehouse_is_low_stock": 1,
        "is_disabled": 0,
        "is_bundle": 0,
        "readable_name": "Fur Jaden Black Tote Bag for Women",
        "image_path": "https:\/\/btesimages.s3.amazonaws.com\/Fur%2BJaden\/h224_black_1.jpg",
        "in_stock": 43,
        "seller_in_stock": 39,
        "marketplace_in_stock": 4,
        "to_ship": 3,
        "product_family": "Tote Bag",
        "hsncode": null,
        "sku_aliases": [
          ["FRJDHDBG00000252", "default"],
          ["H224_Black", "default"]
        ],
        "channels": [{
          "id": 496612323,
          "status_on_channel": 0,
          "price_on_channel": 2500,
          "sku_code_on_channel": "H224_Black",
          "sla_on_channel": 0,
          "quantity_on_channel": 0,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_favamazon.png",
          "channel_title": "Amazon India",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Handbags for Women by Fur Jaden, Black Colour Branded Ladies Casual Tote Bag cum Shoulder Purse with Sling Pouch",
          "item_ref": null,
          "is_fba": 1,
          "channel_id": 11570,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 7,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 509351478,
          "status_on_channel": 0,
          "price_on_channel": 1699,
          "sku_code_on_channel": "H224_Black",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_vilara.png",
          "channel_title": "Vilara",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Black Tote Bag for Women",
          "item_ref": "H224_Black",
          "is_fba": 0,
          "channel_id": 18236,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 41,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 501320601,
          "status_on_channel": 1,
          "price_on_channel": 1699,
          "sku_code_on_channel": "H224_Black",
          "sla_on_channel": 2,
          "quantity_on_channel": 39,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_flipkart.png",
          "channel_title": "Flipkart",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Women Black PU Tote",
          "item_ref": "LSTSLBES4C64FFXNTWMOGCSDI",
          "is_fba": 0,
          "channel_id": 11557,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 17,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 499704481,
          "status_on_channel": 0,
          "price_on_channel": 1360.5,
          "sku_code_on_channel": "FRJDHDBG00000252",
          "sla_on_channel": 0,
          "quantity_on_channel": 40,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_myntra.png",
          "channel_title": "Myntra",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "FUR JADEN_Black_Onesize_H224_Black_FRJDHDBG00000252",
          "item_ref": "FRJDHDBG00000252",
          "is_fba": 0,
          "channel_id": 13056,
          "username": "furjaden01@gmail.com",
          "stock_sync": 0,
          "channel_type_id": 26,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 496269427,
          "status_on_channel": 0,
          "price_on_channel": 1699,
          "sku_code_on_channel": "H224_Black",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 0,
          "favicon_path": "\/img\/icons\/icon_limeroad.png",
          "channel_title": "Limeroad",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "H224_Black",
          "item_ref": "14923862",
          "is_fba": 0,
          "channel_id": 12641,
          "username": "lr_furjaden",
          "stock_sync": 1,
          "channel_type_id": 29,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }, {
          "id": 496263457,
          "status_on_channel": 0,
          "price_on_channel": 1699,
          "sku_code_on_channel": "H224_Black",
          "sla_on_channel": 0,
          "quantity_on_channel": 39,
          "mrp_on_channel": 2500,
          "favicon_path": "\/img\/icons\/icon_paytm.png",
          "channel_title": "Paytm",
          "deduction_shipping_zonal": 0,
          "deduction_shipping_local": 0,
          "title_on_channel": "Fur Jaden Black Tote Bag For Women",
          "item_ref": "103349819",
          "is_fba": 0,
          "channel_id": 12212,
          "username": "furjaden2015@gmail.com",
          "stock_sync": 1,
          "channel_type_id": 21,
          "price_sync_enabled": 0,
          "max_stock": "Stock Not Set"
        }],
        "listings": {
          "11570": {
            "id": 496612323,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 2500,
            "sku_code_on_channel": "H224_Black",
            "quantity_on_channel": 0,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_favamazon.png",
            "channel_title": "Amazon India",
            "title_on_channel": "Handbags for Women by Fur Jaden, Black Colour Branded Ladies Casual Tote Bag cum Shoulder Purse with Sling Pouch",
            "channel_id": 11570,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 7
          },
          "18236": {
            "id": 509351478,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1699,
            "sku_code_on_channel": "H224_Black",
            "quantity_on_channel": 39,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_vilara.png",
            "channel_title": "Vilara",
            "title_on_channel": "Fur Jaden Black Tote Bag for Women",
            "channel_id": 18236,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 41
          },
          "11557": {
            "id": 501320601,
            "status_on_channel": 1,
            "url_on_channel": "http:\/\/www.flipkart.com\/item\/SLBES4C64FFXNTWM",
            "price_on_channel": 1699,
            "sku_code_on_channel": "H224_Black",
            "quantity_on_channel": 39,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_flipkart.png",
            "channel_title": "Flipkart",
            "title_on_channel": "Fur Jaden Women Black PU Tote",
            "channel_id": 11557,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 17
          },
          "13056": {
            "id": 499704481,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1360.5,
            "sku_code_on_channel": "FRJDHDBG00000252",
            "quantity_on_channel": 40,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_myntra.png",
            "channel_title": "Myntra",
            "title_on_channel": "FUR JADEN_Black_Onesize_H224_Black_FRJDHDBG00000252",
            "channel_id": 13056,
            "username": "furjaden01@gmail.com",
            "channel_type_id": 26
          },
          "12641": {
            "id": 496269427,
            "status_on_channel": 0,
            "url_on_channel": null,
            "price_on_channel": 1699,
            "sku_code_on_channel": "H224_Black",
            "quantity_on_channel": 39,
            "mrp_on_channel": 0,
            "favicon_path": "\/img\/icons\/icon_limeroad.png",
            "channel_title": "Limeroad",
            "title_on_channel": "H224_Black",
            "channel_id": 12641,
            "username": "lr_furjaden",
            "channel_type_id": 29
          },
          "12212": {
            "id": 496263457,
            "status_on_channel": 0,
            "url_on_channel": "https:\/\/paytm.com\/shop\/p\/fur-jaden-black-tote-bag-for-women-BAGFUR-JADEN-BLFUR-1341418E193B62",
            "price_on_channel": 1699,
            "sku_code_on_channel": "H224_Black",
            "quantity_on_channel": 39,
            "mrp_on_channel": 2500,
            "favicon_path": "\/img\/icons\/icon_paytm.png",
            "channel_title": "Paytm",
            "title_on_channel": "Fur Jaden Black Tote Bag For Women",
            "channel_id": 12212,
            "username": "furjaden2015@gmail.com",
            "channel_type_id": 21
          }
        }
      }],
      "count": null
    }
  };

  private defaultHeaders = {};

  constructor(private appservice: AppService) {
    console.log('Hello SkuDetailsServiceProvider Provider');
  }

  /*
   abvPrice:
   abvQty:
   blwPrice:
   blwQty:
   limit:10
   page:1
   pfFilter:
   sku:
   skuFilter:sku
   sortField:sellable
   sortType:DESC
   type:to_ship
   whsFilter:
   */

  getSKUDetailsDummy() {
    return this.data;
  }

  getSKUDetails(params: object) {

    let url = 'http://btapp2.ajency.in/skus/getSkuDetails?abvPrice=&abvQty=&blwPrice=&blwQty=&limit=10&page=1&pfFilter=&sku=&skuFilter=sku&sortField=sellable&sortType=DESC&type=to_ship&whsFilter=';
    return this.appservice.request(url,'get',params,this.defaultHeaders);

  }
}
